In [6]:
import torch
if torch.cuda.is_available():
    device=torch.device('cuda')

In [7]:
x=torch.rand(3,requires_grad=True)
print(x)

tensor([0.0124, 0.6998, 0.8888], requires_grad=True)


In [26]:
#specifying requires_grad=True is must to do backward propogation
#it creates vector jacobian product aka chain-rule
z=x*2
print(z)
y=z*z*2
y=y.mean()
print(y)

tensor([0.0248, 1.3996, 1.7777], grad_fn=<MulBackward0>)
tensor(3.4130, grad_fn=<MeanBackward0>)


In [27]:
y.backward() #dy/dx
print(x.grad)

tensor([ 0.2648, 14.9287, 18.9620])


In [34]:
#dummy model
weights=torch.ones(3,requires_grad=True)
for e in range(5):
    m_output=(weights*5).sum()
    m_output.backward()
    print(weights.grad)
    
    #initializing weights to zero again
    weights.grad.zero_()

tensor([5., 5., 5.])
tensor([5., 5., 5.])
tensor([5., 5., 5.])
tensor([5., 5., 5.])
tensor([5., 5., 5.])


In [45]:
#backpropogation 
x=torch.tensor(3.0,requires_grad=True)
y=torch.tensor(2.0,requires_grad=True)
weights=torch.tensor(1.0,requires_grad=True)

#forward pass and compute loss
y_hat=weights*x
loss=(y_hat-y)**2
print(loss)


#backward pass now
loss.backward()
print(weights.grad)


#update weights and keep doing

tensor(1., grad_fn=<PowBackward0>)
tensor(6.)
