In [48]:
import torch
if torch.cuda.is_available():
    device=torch.device('cuda')
    print(torch.cuda.get_device_name(0))

NVIDIA GeForce GTX 1050 Ti


In [7]:
x=torch.empty(2,2)
print(x)

tensor([[9.9347e-36, 0.0000e+00],
        [9.5287e-36, 0.0000e+00]])


In [8]:
x=torch.rand(2,2)
print(x)

tensor([[0.1607, 0.1411],
        [0.3442, 0.2831]])


In [17]:
#Zeros, ones and dtypes
x=torch.zeros(2,2)
print(x)
print('Ones tensor')
y=torch.ones(2,2)
print(y)
z=torch.rand(3,4,dtype=torch.float64)
print(z)
print(z.size())
print(z.dtype)

tensor([[0., 0.],
        [0., 0.]])
Ones tensor
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.5264, 0.7893, 0.9411, 0.7984],
        [0.3105, 0.4593, 0.3589, 0.6618],
        [0.0710, 0.4043, 0.8875, 0.0122]], dtype=torch.float64)
torch.Size([3, 4])
torch.float64


In [22]:
#Addition element wise additon
z=torch.rand(3,4,dtype=torch.float64)
k=torch.rand(3,4,dtype=torch.float64)
q=z+k
print(q)

#also can use add dunction
print("ADDition using add function")
o=torch.add(z,k)
print(o)

tensor([[0.7797, 0.9423, 1.8831, 0.5328],
        [0.9211, 1.0933, 0.1422, 1.7598],
        [0.2904, 0.9091, 0.5092, 0.9013]], dtype=torch.float64)
ADDition using add function
tensor([[0.7797, 0.9423, 1.8831, 0.5328],
        [0.9211, 1.0933, 0.1422, 1.7598],
        [0.2904, 0.9091, 0.5092, 0.9013]], dtype=torch.float64)


In [23]:
#Subtraction element wise additon
z=torch.rand(3,4,dtype=torch.float64)
k=torch.rand(3,4,dtype=torch.float64)
q=z-k
print(q)

#sub can use add dunction
print("Subtraction using add function")
o=torch.sub(z,k)
print(o)

tensor([[ 0.0731,  0.0187,  0.7306, -0.6911],
        [ 0.2249, -0.2251, -0.1945, -0.0934],
        [-0.5197, -0.9290, -0.0054, -0.1484]], dtype=torch.float64)
ADDition using add function
tensor([[ 0.0731,  0.0187,  0.7306, -0.6911],
        [ 0.2249, -0.2251, -0.1945, -0.0934],
        [-0.5197, -0.9290, -0.0054, -0.1484]], dtype=torch.float64)


In [24]:
#multiplication element wise additon
z=torch.rand(3,4,dtype=torch.float64)
k=torch.rand(3,4,dtype=torch.float64)
q=z*k
print(q)

#mul can use add dunction
print("Multiplication using add function")
o=torch.mul(z,k)
print(o)

tensor([[0.5771, 0.2070, 0.0706, 0.7185],
        [0.3488, 0.3338, 0.0788, 0.0264],
        [0.1024, 0.3192, 0.0220, 0.0143]], dtype=torch.float64)
ADDition using add function
tensor([[0.5771, 0.2070, 0.0706, 0.7185],
        [0.3488, 0.3338, 0.0788, 0.0264],
        [0.1024, 0.3192, 0.0220, 0.0143]], dtype=torch.float64)


In [25]:
#divison element wise additon
z=torch.rand(3,4,dtype=torch.float64)
k=torch.rand(3,4,dtype=torch.float64)
q=z/k
print(q)

#mul can use add dunction
print("Division using add function")
o=torch.div(z,k)
print(o)

tensor([[ 0.4044,  0.3823,  0.5352,  6.5340],
        [ 1.2357,  1.7091, 11.4855,  1.9552],
        [ 1.3658,  4.4072,  6.0760,  0.4397]], dtype=torch.float64)
ADDition using add function
tensor([[ 0.4044,  0.3823,  0.5352,  6.5340],
        [ 1.2357,  1.7091, 11.4855,  1.9552],
        [ 1.3658,  4.4072,  6.0760,  0.4397]], dtype=torch.float64)


In [37]:
#slicing
x=torch.rand(5,3)
print(x)
print('slicing from 2 to second last')
print(x[2:-1])
print('only column 0')
print(x[:,0])


tensor([[0.9825, 0.7189, 0.4700],
        [0.3791, 0.6701, 0.4486],
        [0.2516, 0.8652, 0.4468],
        [0.8602, 0.3586, 0.5551],
        [0.9496, 0.8400, 0.5227]])
slicing from 2 to second last
tensor([[0.2516, 0.8652, 0.4468],
        [0.8602, 0.3586, 0.5551]])
only column 0
tensor([0.9825, 0.3791, 0.2516, 0.8602, 0.9496])


tensor([[0.9825, 0.3791, 0.2516, 0.8602, 0.9496],
        [0.7189, 0.6701, 0.8652, 0.3586, 0.8400],
        [0.4700, 0.4486, 0.4468, 0.5551, 0.5227]])

In [38]:
#transpose tensor
x=torch.rand(6,2)
print(x)

z=torch.t(x)
print(z)

tensor([[0.0835, 0.8411],
        [0.6163, 0.0566],
        [0.5425, 0.0013],
        [0.3668, 0.6913],
        [0.5063, 0.3539],
        [0.2848, 0.0651]])
tensor([[0.0835, 0.6163, 0.5425, 0.3668, 0.5063, 0.2848],
        [0.8411, 0.0566, 0.0013, 0.6913, 0.3539, 0.0651]])
